name: C/C++ CI

on:
 push:
  branches: [ main ]
 pull_request:
  branches: [ main ]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: install cppunit
        run: sudo apt install -y libcppunit-dev
      - name: configure
        run: bash ./configure
      - name: make
        run: make
      - name: make test
        run: make test
